// study-vue/src/App.vue
<template>
  <div>
    <AddTodoForm :addTodo="addTodo" />
    <TodoList :todos="todos" :toggleTodo="toggleTodo" />
  </div>
</template>

<script>
import AddTodoForm from './components/AddTodoForm'
import TodoList from './components/TodoList'

export default {
  components: { AddTodoForm, TodoList },
  data() {
    return {
      todos: [
        { id: 1, todo: 'タイトル', completed: false }
      ]
    }
  },
  methods: {
    toggleTodo(id) {
      const target = this.todos.find(todo => todo.id === id)
      target.completed = !target.completed
    },
    addTodo(value) {
      this.todos = this.todos.concat([{
        id: this.todos.length + 1,
        todo: value,
        completed: false
      }])
    }
  }
};
</script>

<style lang="scss" scoped>
</style>

// study-angular/src/app/app.component.ts
import { Component } from '@angular/core'
import { Todo } from './Todo'

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  todos: Todo[] = [
    { todo: 'タイトル', id: 1, completed: false }
  ]
  value: string = ''

  addTodo({ todo }) {
    this.todos = this.todos.concat([{
      todo,
      id: this.todos[this.todos.length - 1].id + 1,
      completed: false
    }])
  }

  toggleTodo({ id }) {
    const todos = this.todos.concat()
    const targetTodo = todos.find(todo => todo.id === id)
    targetTodo.completed = !targetTodo.completed
    this.todos = todos
  }
}

<app-add-todo-form (addTodo)="addTodo($event)"></app-add-todo-form>
<app-todos [todos]="todos" (toggleTodo)="toggleTodo($event)"></app-todos>
