// study-react/src/App.tsx
import React, { Component } from 'react'
import TodoList from './components/TodoList'
import AddTodoForm from './components/AddTodoForm'

interface Todo {
  title: string,
  id: number,
  completed: boolean
}

interface State {
  todos: Todo[],
  value: string
}

class App extends Component {
  public state: State = {
    todos: [
      {
        title: 'タイトル',
        id: 1,
        completed: false
      }
    ],
    value: ''
  }

  toggleTodo(id: number) {
    const todos = this.state.todos.concat()
    const targetTodo = todos.find(todo => todo.id === id)
    if (targetTodo) {
      targetTodo.completed = !targetTodo.completed
    }
    this.setState({
      todos: todos
    })
  }

  addTodo() {
    this.setState({
      todos: this.state.todos.concat([{
        title: this.state.value,
        id: this.state.todos[this.state.todos.length - 1].id + 1,
        completed: false
      }])
    })
    this.clearValue()
  }

  clearValue() {
    this.setState({
      value: ''
    })
  }

  updateValue(e: any) {
    this.setState({
      value: e.target.value
    })
  }

  render() {
    return (
      <div>
        <AddTodoForm
          value={this.state.value}
          addTodo={this.addTodo.bind(this)}
          updateValue={this.updateValue.bind(this)}
        />
        <TodoList
          todos={this.state.todos}
          toggleTodo={this.toggleTodo.bind(this)}
        />
      </div>
    )
  }
}

export default App

// study-vue/src/App.vue
<template>
  <div>
    <AddTodoForm :addTodo="addTodo" />
    <TodoList :todos="todos" :toggleTodo="toggleTodo" />
  </div>
</template>

<script>
import AddTodoForm from './components/AddTodoForm'
import TodoList from './components/TodoList'

export default {
  components: { AddTodoForm, TodoList },
  data() {
    return {
      todos: [
        { id: 1, todo: 'タイトル', completed: false }
      ]
    }
  },
  methods: {
    toggleTodo(id) {
      const target = this.todos.find(todo => todo.id === id)
      target.completed = !target.completed
    },
    addTodo(value) {
      this.todos = this.todos.concat([{
        id: this.todos.length + 1,
        todo: value,
        completed: false
      }])
    }
  }
};
</script>

<style lang="scss" scoped>
</style>
