// study-react/src/components/TodoList.tsx
import styled from 'styled-components'
import * as React from 'react'
import TodoItem from './TodoItem'

interface Todo {
  title: string,
  id: number,
  completed: boolean
}

interface Props {
  className?: string,
  todos: Array<Todo>,
  toggleTodo: (id: number) => void
}

const TodoList: React.SFC<Props> = ({ className, todos, toggleTodo }) => {
  const todoItems = todos.map(todo => (
    <TodoItem todo={todo.title} key={todo.id} completed={todo.completed} id={todo.id} toggleTodo={toggleTodo} />
  ))
  return (
    <ul className={className}>
      {todoItems}
    </ul>
  )
}

export default styled(TodoList)`
  margin: 0;
  padding: 0;
  list-style: none;
`

// study-vue/src/components/TodoList.vue
<template>
  <ul class="todos">
    <TodoItem
      v-for="todo in todos"
      :key="todo.id"
      :id="todo.id"
      :todo="todo.todo"
      :completed="todo.completed"
      @update="toggleTodo"
    />
  </ul>
</template>

<script>
import TodoItem from './TodoItem'

export default {
  components: { TodoItem },
  props: {
    todos: { type: Array, required: true },
    toggleTodo: { type: Function, required: true }
  }
}
</script>

<style lang="scss" scoped>
.todos {
  margin: 0;
  padding: 0;
  list-style: none;
}
</style>
